### ISSUE TITLE
Add admin page to show stats, logs and listen links

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#126]
Hi,

Thank you for this great project. I have install the project 1.1.1 and is works fine! 
Only i mis the some stats and listen links (m3u8, m3u pls) to use this on other streaming radio's.

Have many questions and i will help to test the Open Cast server.

Best regards,
Michel

**Comment by meyskens** [comment]
The links are already present, for example:

**Comment by meyskens** [comment]
The links are already present, for example:
HLS (if `"hls":true` in config): opencast.radioca.st/streams/64kbps.m3u8
DASH (if `"dash":true` in config): opencast.radioca.st/streams/64kbps.mpd
PLS: opencast.radioca.st/streams/64kbps.pls
M3U: opencast.radioca.st/streams/64kbps.m3u
ASX: opencast.radioca.st/streams/64kbps.asx

I am not sure if I ever documented those (if not should do that), they are visible in our hosted solution of Cast.

Stats are in more detail available via the Icecast/SHOUTcast as well as our own API. Historical stats I don't see in the scope of the Cast project itself (building a database and stuff in might be too much)

**Comment by inetactief** [comment]
Thank you, when i add in config.json  the items
"trustProxy":false,
  **"hls":true,**

I get: 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

And "dash":true,  give

Cast 1.0
Listening on 80
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by meyskens** [comment]
This means ffmpeg is not installed

**Comment by inetactief** [comment]
I have install ffmpeg install on CentOS 7 64bit. (reboot) 
when i check ffmpeg.
[root@Linux54 Cast]# ffmpeg
ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
etc..

Add in: config.json

  "hls": true,
    "dash": true,

When is start the first time: 
[root@Linux54 Cast]# node server.js
Cast 1.0
Listening on 80
stdin err dash [ { Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]
stdin err hls [ { Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]

Second time i start: 
stdin err hls [ Error: This socket is closed
    at Socket._writeGeneric (net.js:729:18)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:707:40)
    at PassThrough.inputStream.on.data (/Cast/intern/streams/hls.js:48:64)
    at emitOne (events.js:121:20)
    at PassThrough.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12) ]
stdin err dash [ { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PassThrough.inputStream.on.data (/Cast/intern/streams/dash.js:58:64)
    at emitOne (events.js:121:20)
    at PassThrough.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PassThrough.Readable.push (_stream_readable.js:208:10)
    at PassThrough.Transform.push (_stream_transform.js:147:32)
    at PassThrough.afterTransform (_stream_transform.js:88:10)
    at PassThrough._transform (_stream_passthrough.js:42:3) code: 'EPIPE' } ]

repeat many times.

**Comment by meyskens** [comment]
Currently we log all errors in the stream going to HLS, ECONNRESET is an input connection being reset from the encoder.

The second one seems like ffmpeg exited, but looking at the version number being a mojor version behind i'm not sure that HLS is supported in that version,
