### ISSUE TITLE
Icecast HTTP parser issue

### ISSUE THREAD

**Issue by meyskens** [innovate-technologies/Cast#258]
**Describe the bug**
A (mis)formed HTTP request to the icecast metadata component can throw a fatal error

**To Reproduce**
Unknown

**Screenshots**
GET /admin/metadata?mode=updinfo&mount=%2Flive%2F128kbps&song=SAMANTHA%20J%20%97%20GYPTIAN%20PICTURE%20-%20CLEAN HTTP/1.0
User-Agent: BASSenc/2.4
Authorization: Basic <>

/opt/cast/intern/inputParser/icecast.js:175
        output[keyValueArray[0]] = decodeURIComponent(keyValueArray[1]);
                                   ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at parseGet (/opt/cast/intern/inputParser/icecast.js:164:36)
    at Socket.c.on.data (/opt/cast/intern/inputParser/icecast.js:51:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Server (please complete the following information):**
 - OS: Debian Stretch
 - Node.js version: 10
 - Distribution type: proprietery k8s image

**Comment by meyskens** [comment]
Fixed by #259
