### ISSUE TITLE
No such file or directory '/key' - How to fix?

### ISSUE THREAD

**Issue by tylermcculloch** [Innovate-Technologies/Cast#9]
^
Error: ENOENT, no such file or directory '/key'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/tmcculloch/Cast/intern/HTTP/server.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadCast (/home/tmcculloch/Cast/server.js:27:18)
tmcculloch@radiolink:~/Cast$ Error: ENOENT, no such file or directory '/key'
    at Object.<anonymous> (/home/tmcculloch/Cast/intern/HTTP/server.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadCast (/home/tmcculloch/Cast/server.js:27:18)

**Comment by meyskens** [comment]
https://cast.readme.io/v1.0/docs/configuring-cast

**Comment by tylermcculloch** [comment]
@meyskens would it be wrong to ask you to be able to install Cast on my server for me? I just can't seem to get it to work.

**Comment by meyskens** [comment]
Therefore we offer https://shoutca.st/cast

**Comment by leoetlino** [comment]
That is out of our scope as an open-source project (and we wouldn't want to get access to your private server!). Your issue seems to be caused by a wrong configuration. Disable the HTTPS server and it should work fine.

**Comment by tylermcculloch** [comment]
How to disable the HTTPS?

**Comment by meyskens** [comment]
That and much more is in our readme site!
